apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb-app
spec:
  type: NodePort
  selector:
    app: influxdb-app
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 8086
    name: http
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb
  labels:
    app: influxdb-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb-app
spec:
  selector:
    matchLabels:
      app: influxdb-app
  template:
    metadata:
      name: influxdb
      labels:
        app: influxdb-app
    spec:
      containers:
      - name: influxdb
        image: mbourand/influxdb:1.0
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb
        persistentVolumeClaim:
          claimName: influxdb