apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      name: mysql
      labels:
        app: mysql-app
    spec:
      containers:
      - name: mysql
        image: mbourand/mysql:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /mysql
        livenessProbe:
          exec:
            command:
            - sh
            - /liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql