apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana-app
spec:
  type: NodePort
  selector:
    app: grafana-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 3000
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana-app
spec:
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      name: grafana
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: mbourand/grafana:1.0
        ports:
        - containerPort: 3000
          name: http
