apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      name: nginx
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: mbourand/nginx:1.0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        livenessProbe:
          exec:
            command:
            - sh
            - /liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-app
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx-app
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    nodePort: 443
    protocol: TCP
    name: https
  - port: 22
    targetPort: 22
    nodePort: 22
    protocol: TCP
    name: ssh
  selector:
    app: nginx-app