apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress-app
spec:
  type: NodePort
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 5050
    protocol: TCP
    name: wordpress
  selector:
    app: wordpress-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress-app
spec:
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      name: wordpress
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wordpress
        image: mbourand/wordpress:1.0
        ports:
        - containerPort: 5050